cars24demo/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('tracking/', include('tracking.urls'),name='tracking'),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('form', views.form, name='form'),
    ]

user/models.py
from django.db import models
from django.conf import settings
import datetime
# Create your models here.

# class TimeSheet(models.Model):
#     user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     last_login = models.DateTimeField(default=datetime.datetime(0,0,0))
#     last_logout = models.DateTimeField(default=datetime.datetime(0,0,0))
#     timeClocked = models.DurationField(default=0)

user/forms.py
from django import forms

REGION_CHOICES = (("ABC","ABC"), ("DEF","DEF"),("EFG","EFG"))

class DateInput(forms.DateInput):
    input_type = 'date'

class SampleForm(forms.Form):
    email = forms.EmailField(required=True)
    region = forms.ChoiceField(choices = REGION_CHOICES, required=True)
    branch_name = forms.CharField(label='Branch Name', required=True)
    ra_email_id = forms.ChoiceField(choices=REGION_CHOICES, label='RA Email Id', required=True)
    appointment_id = forms.CharField(required=True)
    first_inspection_date = forms.DateField(required=True, widget=DateInput())
    # calls_made = forms.CheckBoxSelectMultiple(choices=RAEGION_CHOICES)
    type_of_lead = forms.RadioSelect(choices=REGION_CHOICES)



user/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import *
# Create your views here.

def index(request):
    return HttpResponse("Hello, world. You're at the User index.")

def form(request):
    if request.method == "POST":
        print("HERE")
        return redirect('user:index')

    form = SampleForm()
    return render(request, 'user/form.html', {'form':form})

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Cars24 Audit Dashboard{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'user/style.css' %}">
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-expand-md bg-dark navbar-dark navbar-fixed-top navbar-cars24">
      <!-- Brand -->
      <div class="container" >
      <a class="navbar-brand" href="#">
          <img class="logo" src="https://static.cars24.com/cars24/images/cars-logo.png?v=1" alt="cars24logo">
      </a>

      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:form' %}">Form</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tracking-dashboard' %}">QA Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Report(RA)</a>
          </li>
        </ul>
      </div>
    </div>
    </nav>

          {% block content %}
          {% endblock %}

    {% block script %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

templates/tracking/dashboard.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <section class="hero">
        <h1 class="heading">Dashboard</h1>
    </section>
    <div class="container">
        <div id="tracking-filters">
            <form method="GET">
                {{ form|crispy }}
                <input type="submit" name="Submit" value="Submit" class="btn btn-secondary" />
            </form>
        </div>
        <div id="tracking-info">
            <p class="font-weight-normal">
                Visitor tracking began on
                {{ track_start_time|date:"Y-m-d H:i:s" }}
            </p>

        </div>
    </div>
        <div id="tracking-stats">
            <div class="container">
            {% include "tracking/snippets/stats.html" %}
            </div>
        </div>
{% endblock %}

templates/tracking/snippets/stats.html
<h2>Visitors</h2>
{% if visitor_stats.total %}
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Total</th>
            <th>Unique</th>
            <th>% Returning Visitor</th>
            <th>Avg. Time on Site</th>
            {% if pageview_stats %}
                <th>Avg. Pages/Visit</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>Registered</th>
            <td>{{ visitor_stats.registered.total }}</td>
            <td>{{ visitor_stats.registered.unique }}</td>
            <td>{{ visitor_stats.registered.return_ratio|floatformat }}%</td>
            <td>{{ visitor_stats.registered.time_on_site|default_if_none:"n/a" }}</td>
            {% if pageview_stats %}
                <td>{{ visitor_stats.registered.pages_per_visit|floatformat|default:"n/a" }}</td>
            {% endif %}
        </tr>

        {% if visitor_stats.guests %}
        <tr>
            <th>Guests</th>
            <td>{{ visitor_stats.guests.total }}</td>
            <td>{{ visitor_stats.guests.unique }}</td>
            <td>{{ visitor_stats.guests.return_ratio|floatformat }}%</td>
            <td>{{ visitor_stats.guests.time_on_site|default_if_none:"n/a" }}</td>
            {% if pageview_stats %}
                <td>{{ visitor_stats.guests.pages_per_visit|floatformat|default:"n/a" }}</td>
            {% endif %}
        </tr>
        <tr>
            <th>Total</th>
            <td>{{ visitor_stats.total }}</td>
            <td>{{ visitor_stats.unique }}</td>
            <td>{{ visitor_stats.return_ratio|floatformat }}%</td>
            <td>{{ visitor_stats.time_on_site|default_if_none:"n/a" }}</td>
            {% if pageview_stats %}
                <td>{{ visitor_stats.pages_per_visit|floatformat|default:"n/a" }}</td>
            {% endif %}
        </tr>
        {% endif %}
    </tbody>
</table>
{% else %}
    <p>No visitor stats available</p>
{% endif %}

<h2>Registered Users</h2>
{% if user_stats %}
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Visits</th>
            <th>Avg. Time on Site</th>
            <th>Avg. Pages/Visit</th>
        </tr>
    </thead>
    <tbody>
        {% for user in user_stats %}
        <tr>
            <th>{% firstof user.get_full_name user %}</th>
            <td>{{ user.visit_count }}</td>
            <td>{{ user.time_on_site|default_if_none:"n/a" }}</td>
            <td>{{ user.pages_per_visit|floatformat|default:"n/a" }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
    <p>No registered user stats available</p>
{% endif %}

{% if pageview_stats %}
<h2>Pageviews</h2>
    {% if pageview_stats.total %}
    <table>
        <thead>
            <tr>
                <th></th>
                <th>Total</th>
                <th>Unique</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Registered</th>
                <td>{{ pageview_stats.registered.total }}</td>
                <td>{{ pageview_stats.registered.unique }}</td>
            </tr>
            {% if pageview_stats.guests %}
            <tr>
                <th>Guests</th>
                <td>{{ pageview_stats.guests.total }}</td>
                <td>{{ pageview_stats.guests.unique }}</td>
            </tr>
            <tr>
                <th>Total</th>
                <td>{{ pageview_stats.total }}</td>
                <td>{{ pageview_stats.unique }}</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
    {% else %}
        <p>No pageview stats available</p>
    {% endif %}
{% endif %}

templates/user/form.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<section class="hero">
    <h1 class="heading"> Audit Form </h1>
</section>

<div class="container">
    <form action="{% url 'user:form' %}" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}